# Generated by Django 2.1.5 on 2020-02-21 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20200221_1934'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='grade',
            new_name='exam_grade',
        ),
    ]
